// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHoNYnCzRtrUddcylXHdsbfBLjYfqujQ',
    appId: '1:748624396267:web:2419247f4a9ad7b98ce3ae',
    messagingSenderId: '748624396267',
    projectId: 'dynastyres-fa62c',
    authDomain: 'dynastyres-fa62c.firebaseapp.com',
    storageBucket: 'dynastyres-fa62c.appspot.com',
    measurementId: 'G-VQJRCT4F96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4Jj_b3qekyNm07NoSuD_vtXlCtMsOzo',
    appId: '1:748624396267:android:26511fdd3e18e1188ce3ae',
    messagingSenderId: '748624396267',
    projectId: 'dynastyres-fa62c',
    storageBucket: 'dynastyres-fa62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtItGG_untm-VTgooQnNm2Po59ua17OiU',
    appId: '1:748624396267:ios:7374b152f701e0f58ce3ae',
    messagingSenderId: '748624396267',
    projectId: 'dynastyres-fa62c',
    storageBucket: 'dynastyres-fa62c.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
